[package]
name = "bombay-machine-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Ordered concurrent execution for composable representable machines."
keywords = ["concurrency", "interpreter", "state-machine"]
categories = ["concurrency"]

[dependencies]
bombay-transition.workspace = true
thiserror.workspace = true

[dev-dependencies]
loom = "0.7.2"

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"

[lints]
workspace = true
